//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyofITSpecialists.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.UserSchedule = new HashSet<UserSchedule>();
        }
    
        public int Id { get; set; }
        public int IdTime { get; set; }
        public int IdWeek { get; set; }
        public int IdGroup { get; set; }
    
        public virtual ClassTime ClassTime { get; set; }
        public virtual DayOfTheWeek DayOfTheWeek { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSchedule> UserSchedule { get; set; }
    }
}
