//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyofITSpecialists.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int IdDayOfTheWeek { get; set; }
        public int IdTime { get; set; }
        public int IdGroup { get; set; }
        public int IdUser { get; set; }
        public int IdSubject { get; set; }
    
        public virtual ClassTime ClassTime { get; set; }
        public virtual DayOfTheWeek DayOfTheWeek { get; set; }
        public virtual Group Group { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
