//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyofITSpecialists.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRecords
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdRecords { get; set; }
    
        public virtual Records Records { get; set; }
        public virtual User User { get; set; }
    }
}
